name: product-catalog-ci

on:
  push:
    branches: ["main"]
  

env:
  # Force testing against Node.js 24 runtime now
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go (latest stable)
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Verify Go version
        run: go version

      - name: Download dependencies
        working-directory: src/product-catalog
        run: |
          go mod tidy
          go mod download

      - name: Build application
        working-directory: src/product-catalog
        run: go build -v -o app main.go

      - name: Run unit tests
        working-directory: src/product-catalog
        run: go test ./... -v


  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go (latest stable)
        uses: actions/setup-go@v4
        with:
           go-version: 'stable'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6   # Node20 compatible
        with:
          version: v1.55.2
          run: golangci-lint run
          working-directory: src/product-catalog


  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Node20 compatible

      - name: Login to Docker Hub
        uses: docker/login-action@v3         # Node20 compatible
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v6     # Node20 compatible
        with:
          context: src/product-catalog
          file: src/product-catalog/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
            ${{ secrets.DOCKER_USERNAME }}/product-catalog:latest


  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code (GitOps Repo)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CICD_GITHUB_TOKEN }}

      - name: Update Kubernetes deployment tag
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}|" \
            kubernetes/productcatalog/deploy.yaml

      - name: Commit and push manifest updates
        run: |
          git config --global user.email "michaelo.ray06@gmail.com"
          git config --global user.name "MichaelRay06"

          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "[CI]: Update product catalog image tag to ${{ github.run_id }}"
          git push origin HEAD:main


